version: '3.8'

services:
  mysql_test:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: test_root_password
      MYSQL_DATABASE: article_manager_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      TZ: 'Asia/Tokyo'
    ports:
      - "3307:3306"
    volumes:
      - ./db/test_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - test_article_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-utest_user", "-ptest_password"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  test_article_network:
    driver: bridge
